#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Moodis.Resource", IsApplication=true)]

namespace Moodis
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F020000
			public const int gravity_unit_0x = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int gravity_unit_100x = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int gravity_unit_50x = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int grid_unit_0x = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int grid_unit_100x = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int grid_unit_104x = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int grid_unit_10x = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int grid_unit_10x_half = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int grid_unit_110x = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int grid_unit_114x = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int grid_unit_116x = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int grid_unit_11x = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int grid_unit_120x = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int grid_unit_128x = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int grid_unit_12x = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int grid_unit_132x = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int grid_unit_134x = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int grid_unit_136x = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int grid_unit_13x = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int grid_unit_144x = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int grid_unit_14x = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int grid_unit_15x = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int grid_unit_168x = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int grid_unit_16x = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int grid_unit_17x = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int grid_unit_180x = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int grid_unit_18x = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int grid_unit_190x = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int grid_unit_19x = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int grid_unit_1x = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int grid_unit_20x = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int grid_unit_21x = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int grid_unit_22x = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int grid_unit_23x = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int grid_unit_24x = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int grid_unit_25x = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int grid_unit_26x = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int grid_unit_278x = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int grid_unit_28x = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int grid_unit_2x = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int grid_unit_30x = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int grid_unit_32x = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int grid_unit_33x = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int grid_unit_35x = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int grid_unit_36x = 2130837548;
			
			// aapt resource value: 0x7F02002D
			public const int grid_unit_38x = 2130837549;
			
			// aapt resource value: 0x7F02002E
			public const int grid_unit_3x = 2130837550;
			
			// aapt resource value: 0x7F02002F
			public const int grid_unit_40x = 2130837551;
			
			// aapt resource value: 0x7F020030
			public const int grid_unit_41x = 2130837552;
			
			// aapt resource value: 0x7F020031
			public const int grid_unit_42x = 2130837553;
			
			// aapt resource value: 0x7F020032
			public const int grid_unit_44x = 2130837554;
			
			// aapt resource value: 0x7F020033
			public const int grid_unit_45x = 2130837555;
			
			// aapt resource value: 0x7F020034
			public const int grid_unit_48x = 2130837556;
			
			// aapt resource value: 0x7F020035
			public const int grid_unit_4x = 2130837557;
			
			// aapt resource value: 0x7F020036
			public const int grid_unit_50x = 2130837558;
			
			// aapt resource value: 0x7F020037
			public const int grid_unit_52x = 2130837559;
			
			// aapt resource value: 0x7F020038
			public const int grid_unit_54x = 2130837560;
			
			// aapt resource value: 0x7F020039
			public const int grid_unit_55x = 2130837561;
			
			// aapt resource value: 0x7F02003A
			public const int grid_unit_56x = 2130837562;
			
			// aapt resource value: 0x7F02003B
			public const int grid_unit_58x = 2130837563;
			
			// aapt resource value: 0x7F02003C
			public const int grid_unit_5x = 2130837564;
			
			// aapt resource value: 0x7F02003D
			public const int grid_unit_60x = 2130837565;
			
			// aapt resource value: 0x7F02003E
			public const int grid_unit_62x = 2130837566;
			
			// aapt resource value: 0x7F02003F
			public const int grid_unit_64x = 2130837567;
			
			// aapt resource value: 0x7F020040
			public const int grid_unit_68x = 2130837568;
			
			// aapt resource value: 0x7F020041
			public const int grid_unit_6x = 2130837569;
			
			// aapt resource value: 0x7F020042
			public const int grid_unit_72x = 2130837570;
			
			// aapt resource value: 0x7F020043
			public const int grid_unit_75x = 2130837571;
			
			// aapt resource value: 0x7F020044
			public const int grid_unit_76x = 2130837572;
			
			// aapt resource value: 0x7F020045
			public const int grid_unit_7x = 2130837573;
			
			// aapt resource value: 0x7F020046
			public const int grid_unit_80x = 2130837574;
			
			// aapt resource value: 0x7F020047
			public const int grid_unit_82x = 2130837575;
			
			// aapt resource value: 0x7F020048
			public const int grid_unit_88x = 2130837576;
			
			// aapt resource value: 0x7F020049
			public const int grid_unit_8x = 2130837577;
			
			// aapt resource value: 0x7F02004A
			public const int grid_unit_96x = 2130837578;
			
			// aapt resource value: 0x7F02004B
			public const int grid_unit_9x = 2130837579;
			
			// aapt resource value: 0x7F02004C
			public const int grid_unit_half = 2130837580;
			
			// aapt resource value: 0x7F02004D
			public const int login_header = 2130837581;
			
			// aapt resource value: 0x7F02004E
			public const int menu_buttons = 2130837582;
			
			// aapt resource value: 0x7F02004F
			public const int negative_grid_unit_12x = 2130837583;
			
			// aapt resource value: 0x7F020050
			public const int negative_grid_unit_4x = 2130837584;
			
			// aapt resource value: 0x7F020051
			public const int regular_text = 2130837585;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int baseline_error_24 = 2130903040;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public const int camera_preview = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int content_frame = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int goToCalendar = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int goToCamera = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int groups = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int header = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int imageForView = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int lblAnger = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int lblContempt = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int lblDisgust = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int lblFear = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int lblHappiness = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int lblNeutral = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int lblSadness = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int lblSurprise = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int passwordInput = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int passwordLabel = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int playMusic = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int registerButton = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int signInButton = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int signInFaceButton = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int StopMusic = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int takePictureButton = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int usernameInput = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int usernameLabel = 2130968600;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public const int activity_camera = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int activity_history = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int activity_main = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int activity_menu = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int activity_signin = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int fragment_camera = 2131034117;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F060000
			public const int baseline_error_black_18 = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int baseline_error_black_24 = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int baseline_error_black_36 = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int baseline_error_black_48 = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int ic_launcher = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int ic_launcher_foreground = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int ic_launcher_round = 2131099654;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F070000
			public const int action_settings = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int calendar_button = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int groups_button = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int loading = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int non_existant_preview = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int ok = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int password_empty_error = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int permissions_not_granted = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int permission_available_camera = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int permission_camera_rationale = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int picture_button = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int placeholder = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int play_music_button = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int signin_button_text = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public const int signin_face_button_text = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int signin_password_label = 2131165200;
			
			// aapt resource value: 0x7F070011
			public const int signin_register_button_text = 2131165201;
			
			// aapt resource value: 0x7F070012
			public const int signin_username_label = 2131165202;
			
			// aapt resource value: 0x7F070013
			public const int stop_music_button = 2131165203;
			
			// aapt resource value: 0x7F070014
			public const int take_another_picture = 2131165204;
			
			// aapt resource value: 0x7F070015
			public const int username_empty_error = 2131165205;
			
			// aapt resource value: 0x7F070016
			public const int user_not_found_error = 2131165206;
			
			// aapt resource value: 0x7F070017
			public const int warning_face_detection = 2131165207;
			
			// aapt resource value: 0x7F070018
			public const int warning_in_request = 2131165208;
			
			// aapt resource value: 0x7F070019
			public const int warning_playing_music = 2131165209;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F080000
			public const int AppTheme = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
